name: 🐛 Bug Report
description: Report a bug or issue with the RPM IQ Exam app
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the information below to help us investigate and fix the issue.

  - type: textarea
    id: bug-description
    attributes:
      label: 🐛 Bug Description
      description: A clear and concise description of the bug
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 📋 Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ Expected Behavior
      description: What you expected to happen
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: ❌ Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened instead
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: 🌐 Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other (please specify in additional context)
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: Browser Version
      description: What version of the browser are you using?
      placeholder: e.g., Chrome 118.0.5993.88
    validations:
      required: true

  - type: dropdown
    id: device-type
    attributes:
      label: 📱 Device Type
      description: What type of device are you using?
      options:
        - Desktop/Laptop
        - Mobile Phone
        - Tablet
        - Other
    validations:
      required: true

  - type: input
    id: operating-system
    attributes:
      label: 💻 Operating System
      description: What operating system are you using?
      placeholder: e.g., Windows 11, macOS 14.0, Ubuntu 22.04, iOS 17.0, Android 13
    validations:
      required: true

  - type: textarea
    id: screen-size
    attributes:
      label: 📐 Screen Size/Resolution
      description: What is your screen size or resolution?
      placeholder: e.g., 1920x1080, Mobile 375x667, etc.

  - type: textarea
    id: console-errors
    attributes:
      label: 🔍 Console Errors
      description: Any error messages in the browser console? (Press F12 → Console tab)
      placeholder: Paste any console errors here
      render: text

  - type: textarea
    id: screenshots
    attributes:
      label: 📷 Screenshots
      description: If applicable, add screenshots to help explain the problem

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might help us understand the issue

  - type: checkboxes
    id: checklist
    attributes:
      label: ☑️ Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all the requested information above
          required: true
        - label: I understand this is for bug reports only (not feature requests or questions)
          required: true